// EW perk pool: vanilla perks minus not_in_default_perk_pool=true and EW-hidden perks
// Excluded: MOON_RADAR, MAP, LEGGY_FEET (vanilla), SAVING_GRACE, RESPAWN (EW)
const PERK_POOL = [
  { id: 'CRITICAL_HIT', name: 'Critical Hit +' },
  { id: 'BREATH_UNDERWATER', name: 'Breathless' },
  { id: 'EXTRA_MONEY', name: 'Greed' },
  { id: 'EXTRA_MONEY_TRICK_KILL', name: 'Trick Greed' },
  { id: 'GOLD_IS_FOREVER', name: 'Gold Is Forever' },
  { id: 'TRICK_BLOOD_MONEY', name: 'Trick Blood Money' },
  { id: 'EXPLODING_GOLD', name: 'Exploding Gold' },
  { id: 'HOVER_BOOST', name: 'Strong Levitation' },
  { id: 'FASTER_LEVITATION', name: 'Faster Levitation' },
  { id: 'MOVEMENT_FASTER', name: 'Faster Movement' },
  { id: 'STRONG_KICK', name: 'Never Skip Leg Day' },
  { id: 'TELEKINESIS', name: 'Telekinetic Kick' },
  { id: 'REPELLING_CAPE', name: 'Repelling Cape' },
  { id: 'EXPLODING_CORPSES', name: 'Exploding Corpses' },
  { id: 'INVISIBILITY', name: 'Invisibility' },
  { id: 'GLOBAL_GORE', name: 'More Blood' },
  { id: 'REMOVE_FOG_OF_WAR', name: 'All-Seeing Eye' },
  { id: 'LEVITATION_TRAIL', name: 'Levitation Trail' },
  { id: 'VAMPIRISM', name: 'Vampirism' },
  { id: 'EXTRA_HP', name: 'Extra Health' },
  { id: 'HEARTS_MORE_EXTRA_HP', name: 'Stronger Hearts' },
  { id: 'GLASS_CANNON', name: 'Glass Cannon' },
  { id: 'LOW_HP_DAMAGE_BOOST', name: 'Living on the Edge' },
  { id: 'WORM_ATTRACTOR', name: 'Worm Attractor' },
  { id: 'RADAR_ENEMY', name: 'Enemy Radar' },
  { id: 'FOOD_CLOCK', name: 'Eat Your Vegetables' },
  { id: 'IRON_STOMACH', name: 'Iron Stomach' },
  { id: 'WAND_RADAR', name: 'Wand Radar' },
  { id: 'ITEM_RADAR', name: 'Item Radar' },
  { id: 'PROTECTION_FIRE', name: 'Fire Immunity' },
  { id: 'PROTECTION_RADIOACTIVITY', name: 'Toxic Immunity' },
  { id: 'PROTECTION_EXPLOSION', name: 'Explosion Immunity' },
  { id: 'PROTECTION_MELEE', name: 'Melee Immunity' },
  { id: 'PROTECTION_ELECTRICITY', name: 'Electricity Immunity' },
  { id: 'TELEPORTITIS', name: 'Teleportitis' },
  { id: 'TELEPORTITIS_DODGE', name: 'Teleportitis Dodge' },
  { id: 'STAINLESS_ARMOUR', name: 'Stainless Armour' },
  { id: 'EDIT_WANDS_EVERYWHERE', name: 'Tinker With Wands Everywhere' },
  { id: 'NO_WAND_EDITING', name: 'No Wand Tinkering' },
  { id: 'WAND_EXPERIMENTER', name: 'Wand Experimenter' },
  { id: 'ADVENTURER', name: 'Healthy Exploration' },
  { id: 'ABILITY_ACTIONS_MATERIALIZED', name: 'Bombs Materialized' },
  { id: 'PROJECTILE_HOMING', name: 'Homing Shots' },
  { id: 'PROJECTILE_HOMING_SHOOTER', name: 'Boomerang Spells' },
  { id: 'UNLIMITED_SPELLS', name: 'Unlimited Spells' },
  { id: 'FREEZE_FIELD', name: 'Freeze Field' },
  { id: 'FIRE_GAS', name: 'Gas Fire' },
  { id: 'DISSOLVE_POWDERS', name: 'Dissolve Powders' },
  { id: 'BLEED_SLIME', name: 'Slime Blood' },
  { id: 'BLEED_OIL', name: 'Oil Blood' },
  { id: 'BLEED_GAS', name: 'Gas Blood' },
  { id: 'SHIELD', name: 'Permanent Shield' },
  { id: 'REVENGE_EXPLOSION', name: 'Revenge Explosion' },
  { id: 'REVENGE_TENTACLE', name: 'Revenge Tentacle' },
  { id: 'REVENGE_RATS', name: 'Revenge Rats' },
  { id: 'REVENGE_BULLET', name: 'Revenge Bullets' },
  { id: 'ATTACK_FOOT', name: 'Lukki Mutation' },
  { id: 'PLAGUE_RATS', name: 'Plague Rats' },
  { id: 'VOMIT_RATS', name: 'Spontaneous Generation' },
  { id: 'CORDYCEPS', name: 'Cordyceps' },
  { id: 'MOLD', name: 'Fungal Colony' },
  { id: 'WORM_SMALLER_HOLES', name: 'Feared by Worms' },
  { id: 'PROJECTILE_REPULSION', name: 'Projectile Repulsion Field' },
  { id: 'RISKY_CRITICAL', name: 'Close Call' },
  { id: 'FUNGAL_DISEASE', name: 'Fungal Disease' },
  { id: 'PROJECTILE_SLOW_FIELD', name: 'Projectile Slower' },
  { id: 'PROJECTILE_REPULSION_SECTOR', name: 'Projectile Repulsion Sector' },
  { id: 'PROJECTILE_EATER_SECTOR', name: 'Projectile Eater' },
  { id: 'ORBIT', name: 'Phasing' },
  { id: 'ANGRY_GHOST', name: 'Angry Ghost' },
  { id: 'HUNGRY_GHOST', name: 'Hungry Ghost' },
  { id: 'DEATH_GHOST', name: 'Mournful Spirit' },
  { id: 'HOMUNCULUS', name: 'Homunculus' },
  { id: 'LUKKI_MINION', name: 'Lukki Minion' },
  { id: 'ELECTRICITY', name: 'Electricity' },
  { id: 'ATTRACT_ITEMS', name: 'Attract Gold' },
  { id: 'EXTRA_KNOCKBACK', name: 'Extra Knockback on Spells' },
  { id: 'LOWER_SPREAD', name: 'Concentrated Spells' },
  { id: 'LOW_RECOIL', name: 'Low Recoil' },
  { id: 'BOUNCE', name: 'Bouncing Spells' },
  { id: 'FAST_PROJECTILES', name: 'Faster Projectiles' },
  { id: 'ALWAYS_CAST', name: 'Always Cast' },
  { id: 'EXTRA_MANA', name: 'High Mana, Low Capacity' },
  { id: 'NO_MORE_SHUFFLE', name: 'No More Shuffle' },
  { id: 'NO_MORE_KNOCKBACK', name: 'No More Knockback' },
  { id: 'DUPLICATE_PROJECTILE', name: 'Projectile Duplication' },
  { id: 'FASTER_WANDS', name: 'Faster Wands' },
  { id: 'EXTRA_SLOTS', name: 'Extra Wand Capacity' },
  { id: 'CONTACT_DAMAGE', name: 'Contact Damage' },
  { id: 'EXTRA_PERK', name: 'Extra Perk' },
  { id: 'PERKS_LOTTERY', name: 'Perk Lottery' },
  { id: 'GAMBLE', name: 'Gamble' },
  { id: 'EXTRA_SHOP_ITEM', name: 'Extra Item In Holy Mountain' },
  { id: 'GENOME_MORE_HATRED', name: 'More Hatred' },
  { id: 'GENOME_MORE_LOVE', name: 'More Love' },
  { id: 'PEACE_WITH_GODS', name: 'Peace with Gods' },
  { id: 'MANA_FROM_KILLS', name: 'Kills to Mana' },
  { id: 'ANGRY_LEVITATION', name: 'Rage-fueled Levitation' },
  { id: 'LASER_AIM', name: 'Pinpointer' },
  { id: 'PERSONAL_LASER', name: 'Personal Plasma Beam' },
  { id: 'MEGA_BEAM_STONE', name: 'Summon Sädekivi' },
];

if (typeof module !== 'undefined') module.exports = { PERK_POOL };
