// Noita EW perk pool — noita-tools perks.json order, not_in_default_perk_pool excluded
// Excluded: MOON_RADAR, MAP, LEGGY_FEET (vanilla not_in_default_perk_pool)
// SAVING_GRACE and RESPAWN remain: EW hide_perk() hides them from UI but not from the deck

var PERK_POOL = [
  { id: 'CRITICAL_HIT',                  name: 'Critical Hit +',               stackable: true,  rare: false, maxPool: null },
  { id: 'BREATH_UNDERWATER',             name: 'Breathless',                   stackable: true,  rare: true,  maxPool: null },
  { id: 'EXTRA_MONEY',                   name: 'Greed',                        stackable: true,  rare: false, maxPool: null },
  { id: 'EXTRA_MONEY_TRICK_KILL',        name: 'Trick Greed',                  stackable: true,  rare: false, maxPool: null },
  { id: 'GOLD_IS_FOREVER',              name: 'Gold Is Forever',              stackable: false, rare: false, maxPool: null },
  { id: 'TRICK_BLOOD_MONEY',            name: 'Trick Blood Money',            stackable: false, rare: false, maxPool: null },
  { id: 'EXPLODING_GOLD',               name: 'Exploding Gold',               stackable: true,  rare: true,  maxPool: 1    },
  { id: 'HOVER_BOOST',                  name: 'Strong Levitation',            stackable: true,  rare: false, maxPool: 1    },
  { id: 'FASTER_LEVITATION',            name: 'Faster Levitation',            stackable: true,  rare: false, maxPool: 1    },
  { id: 'MOVEMENT_FASTER',              name: 'Faster Movement',              stackable: true,  rare: false, maxPool: 2    },
  { id: 'STRONG_KICK',                  name: 'Never Skip Leg Day',           stackable: true,  rare: false, maxPool: 1    },
  { id: 'TELEKINESIS',                  name: 'Telekinetic Kick',             stackable: false, rare: false, maxPool: null },
  { id: 'REPELLING_CAPE',               name: 'Repelling Cape',               stackable: true,  rare: true,  maxPool: 2    },
  { id: 'EXPLODING_CORPSES',            name: 'Exploding Corpses',            stackable: false, rare: false, maxPool: null },
  { id: 'SAVING_GRACE',                 name: 'Saving Grace',                 stackable: false, rare: false, maxPool: null },
  { id: 'INVISIBILITY',                 name: 'Invisibility',                 stackable: false, rare: false, maxPool: null },
  { id: 'GLOBAL_GORE',                  name: 'More Blood',                   stackable: true,  rare: false, maxPool: 1    },
  { id: 'REMOVE_FOG_OF_WAR',            name: 'All-Seeing Eye',               stackable: false, rare: false, maxPool: null },
  { id: 'LEVITATION_TRAIL',             name: 'Levitation Trail',             stackable: true,  rare: true,  maxPool: 2    },
  { id: 'VAMPIRISM',                    name: 'Vampirism',                    stackable: false, rare: false, maxPool: null },
  { id: 'EXTRA_HP',                     name: 'Extra Health',                 stackable: true,  rare: false, maxPool: 3    },
  { id: 'HEARTS_MORE_EXTRA_HP',         name: 'Stronger Hearts',              stackable: true,  rare: true,  maxPool: 2    },
  { id: 'GLASS_CANNON',                 name: 'Glass Cannon',                 stackable: true,  rare: true,  maxPool: 2    },
  { id: 'LOW_HP_DAMAGE_BOOST',          name: 'Living on the Edge',           stackable: true,  rare: true,  maxPool: 2    },
  { id: 'RESPAWN',                      name: 'Immortal',                     stackable: true,  rare: true,  maxPool: null },
  { id: 'WORM_ATTRACTOR',               name: 'Worm Attractor',               stackable: true,  rare: true,  maxPool: null },
  { id: 'RADAR_ENEMY',                  name: 'Enemy Radar',                  stackable: false, rare: false, maxPool: null },
  { id: 'FOOD_CLOCK',                   name: 'Eat Your Vegetables',          stackable: false, rare: false, maxPool: null },
  { id: 'IRON_STOMACH',                 name: 'Iron Stomach',                 stackable: false, rare: false, maxPool: null },
  { id: 'WAND_RADAR',                   name: 'Wand Radar',                   stackable: false, rare: false, maxPool: null },
  { id: 'ITEM_RADAR',                   name: 'Item Radar',                   stackable: false, rare: false, maxPool: null },
  // MOON_RADAR excluded (not_in_default_perk_pool)
  // MAP excluded (not_in_default_perk_pool)
  { id: 'PROTECTION_FIRE',              name: 'Fire Immunity',                stackable: false, rare: false, maxPool: null },
  { id: 'PROTECTION_RADIOACTIVITY',     name: 'Toxic Immunity',               stackable: false, rare: false, maxPool: null },
  { id: 'PROTECTION_EXPLOSION',         name: 'Explosion Immunity',           stackable: false, rare: false, maxPool: null },
  { id: 'PROTECTION_MELEE',             name: 'Melee Immunity',               stackable: false, rare: false, maxPool: null },
  { id: 'PROTECTION_ELECTRICITY',       name: 'Electricity Immunity',         stackable: false, rare: false, maxPool: null },
  { id: 'TELEPORTITIS',                 name: 'Teleportitis',                 stackable: false, rare: false, maxPool: null },
  { id: 'TELEPORTITIS_DODGE',           name: 'Teleportitis Dodge',           stackable: false, rare: false, maxPool: null },
  { id: 'STAINLESS_ARMOUR',             name: 'Stainless Armour',             stackable: true,  rare: true,  maxPool: null },
  { id: 'EDIT_WANDS_EVERYWHERE',        name: 'Tinker With Wands Everywhere', stackable: false, rare: false, maxPool: null },
  { id: 'NO_WAND_EDITING',              name: 'No Wand Tinkering',            stackable: false, rare: false, maxPool: null },
  { id: 'WAND_EXPERIMENTER',            name: 'Wand Experimenter',            stackable: true,  rare: true,  maxPool: null },
  { id: 'ADVENTURER',                   name: 'Healthy Exploration',          stackable: false, rare: false, maxPool: null },
  { id: 'ABILITY_ACTIONS_MATERIALIZED', name: 'Bombs Materialized',           stackable: false, rare: false, maxPool: null },
  { id: 'PROJECTILE_HOMING',            name: 'Homing Shots',                 stackable: false, rare: false, maxPool: null },
  { id: 'PROJECTILE_HOMING_SHOOTER',    name: 'Boomerang Spells',             stackable: false, rare: false, maxPool: null },
  { id: 'UNLIMITED_SPELLS',             name: 'Unlimited Spells',             stackable: false, rare: false, maxPool: null },
  { id: 'FREEZE_FIELD',                 name: 'Freeze Field',                 stackable: false, rare: false, maxPool: null },
  { id: 'FIRE_GAS',                     name: 'Gas Fire',                     stackable: false, rare: false, maxPool: null },
  { id: 'DISSOLVE_POWDERS',             name: 'Dissolve Powders',             stackable: false, rare: false, maxPool: null },
  { id: 'BLEED_SLIME',                  name: 'Slime Blood',                  stackable: true,  rare: true,  maxPool: null },
  { id: 'BLEED_OIL',                    name: 'Oil Blood',                    stackable: false, rare: false, maxPool: null },
  { id: 'BLEED_GAS',                    name: 'Gas Blood',                    stackable: false, rare: false, maxPool: null },
  { id: 'SHIELD',                       name: 'Permanent Shield',             stackable: true,  rare: false, maxPool: 2    },
  { id: 'REVENGE_EXPLOSION',            name: 'Revenge Explosion',            stackable: true,  rare: true,  maxPool: null },
  { id: 'REVENGE_TENTACLE',             name: 'Revenge Tentacle',             stackable: true,  rare: true,  maxPool: null },
  { id: 'REVENGE_RATS',                 name: 'Revenge Rats',                 stackable: false, rare: false, maxPool: null },
  { id: 'REVENGE_BULLET',               name: 'Revenge Bullets',              stackable: true,  rare: true,  maxPool: null },
  { id: 'ATTACK_FOOT',                  name: 'Lukki Mutation',               stackable: true,  rare: true,  maxPool: 2    },
  // LEGGY_FEET excluded (not_in_default_perk_pool)
  { id: 'PLAGUE_RATS',                  name: 'Plague Rats',                  stackable: true,  rare: true,  maxPool: 2    },
  { id: 'VOMIT_RATS',                   name: 'Spontaneous Generation',       stackable: false, rare: false, maxPool: null },
  { id: 'CORDYCEPS',                    name: 'Cordyceps',                    stackable: false, rare: false, maxPool: null },
  { id: 'MOLD',                         name: 'Fungal Colony',                stackable: false, rare: false, maxPool: null },
  { id: 'WORM_SMALLER_HOLES',           name: 'Feared by Worms',              stackable: false, rare: false, maxPool: null },
  { id: 'PROJECTILE_REPULSION',         name: 'Projectile Repulsion Field',   stackable: true,  rare: true,  maxPool: null },
  { id: 'RISKY_CRITICAL',               name: 'Close Call',                   stackable: true,  rare: true,  maxPool: 2    },
  { id: 'FUNGAL_DISEASE',               name: 'Fungal Disease',               stackable: true,  rare: true,  maxPool: 2    },
  { id: 'PROJECTILE_SLOW_FIELD',        name: 'Projectile Slower',            stackable: true,  rare: true,  maxPool: null },
  { id: 'PROJECTILE_REPULSION_SECTOR',  name: 'Projectile Repulsion Sector',  stackable: true,  rare: true,  maxPool: null },
  { id: 'PROJECTILE_EATER_SECTOR',      name: 'Projectile Eater',             stackable: false, rare: false, maxPool: null },
  { id: 'ORBIT',                        name: 'Phasing',                      stackable: true,  rare: false, maxPool: 2    },
  { id: 'ANGRY_GHOST',                  name: 'Angry Ghost',                  stackable: true,  rare: false, maxPool: null },
  { id: 'HUNGRY_GHOST',                 name: 'Hungry Ghost',                 stackable: true,  rare: false, maxPool: 2    },
  { id: 'DEATH_GHOST',                  name: 'Mournful Spirit',              stackable: true,  rare: true,  maxPool: null },
  { id: 'HOMUNCULUS',                   name: 'Homunculus',                   stackable: true,  rare: false, maxPool: 2    },
  { id: 'LUKKI_MINION',                 name: 'Lukki Minion',                 stackable: false, rare: false, maxPool: null },
  { id: 'ELECTRICITY',                  name: 'Electricity',                  stackable: false, rare: false, maxPool: null },
  { id: 'ATTRACT_ITEMS',                name: 'Attract Gold',                 stackable: true,  rare: true,  maxPool: 1    },
  { id: 'EXTRA_KNOCKBACK',              name: 'Extra Knockback on Spells',    stackable: true,  rare: true,  maxPool: null },
  { id: 'LOWER_SPREAD',                 name: 'Concentrated Spells',          stackable: true,  rare: true,  maxPool: null },
  { id: 'LOW_RECOIL',                   name: 'Low Recoil',                   stackable: false, rare: false, maxPool: null },
  { id: 'BOUNCE',                       name: 'Bouncing Spells',              stackable: false, rare: false, maxPool: null },
  { id: 'FAST_PROJECTILES',             name: 'Faster Projectiles',           stackable: false, rare: false, maxPool: null },
  { id: 'ALWAYS_CAST',                  name: 'Always Cast',                  stackable: true,  rare: false, maxPool: null },
  { id: 'EXTRA_MANA',                   name: 'High Mana, Low Capacity',      stackable: true,  rare: false, maxPool: null },
  { id: 'NO_MORE_SHUFFLE',              name: 'No More Shuffle',              stackable: false, rare: false, maxPool: null },
  { id: 'NO_MORE_KNOCKBACK',            name: 'No More Knockback',            stackable: false, rare: false, maxPool: null },
  { id: 'DUPLICATE_PROJECTILE',         name: 'Projectile Duplication',       stackable: true,  rare: false, maxPool: null },
  { id: 'FASTER_WANDS',                 name: 'Faster Wands',                 stackable: true,  rare: false, maxPool: null },
  { id: 'EXTRA_SLOTS',                  name: 'Extra Wand Capacity',          stackable: true,  rare: false, maxPool: null },
  { id: 'CONTACT_DAMAGE',               name: 'Contact Damage',               stackable: false, rare: false, maxPool: null },
  { id: 'EXTRA_PERK',                   name: 'Extra Perk',                   stackable: true,  rare: false, maxPool: 3    },
  { id: 'PERKS_LOTTERY',                name: 'Perk Lottery',                 stackable: true,  rare: true,  maxPool: 3    },
  { id: 'GAMBLE',                       name: 'Gamble',                       stackable: true,  rare: false, maxPool: null },
  { id: 'EXTRA_SHOP_ITEM',              name: 'Extra Item In Holy Mountain',  stackable: true,  rare: false, maxPool: 2    },
  { id: 'GENOME_MORE_HATRED',           name: 'More Hatred',                  stackable: true,  rare: false, maxPool: null },
  { id: 'GENOME_MORE_LOVE',             name: 'More Love',                    stackable: true,  rare: false, maxPool: null },
  { id: 'PEACE_WITH_GODS',              name: 'Peace with Gods',              stackable: false, rare: false, maxPool: null },
  { id: 'MANA_FROM_KILLS',              name: 'Kills to Mana',                stackable: false, rare: false, maxPool: null },
  { id: 'ANGRY_LEVITATION',             name: 'Rage-fueled Levitation',       stackable: false, rare: false, maxPool: null },
  { id: 'LASER_AIM',                    name: 'Pinpointer',                   stackable: true,  rare: true,  maxPool: null },
  { id: 'PERSONAL_LASER',               name: 'Personal Plasma Beam',         stackable: true,  rare: true,  maxPool: 2    },
  { id: 'MEGA_BEAM_STONE',              name: 'Summon Sädekivi',         stackable: true,  rare: false, maxPool: null },
];

var PERK_NAME_MAP = (function() {
  var m = {};
  PERK_POOL.forEach(function(p) { m[p.id] = p.name; });
  return m;
})();

if (typeof module !== 'undefined') {
  module.exports = { PERK_POOL, PERK_NAME_MAP };
}
