// Noita EW perk list
// Source: data/scripts/perks/perk_list.lua + quant.ew override_perk_list.lua
// Format: [id, displayName, stackable, maxInPerkPool, stackableIsRare]

var PERK_LIST = [
  ["EXTRA_MANA",                   "Extra Mana",                        true,  10, false],
  ["MANA_FROM_KILLS",              "Mana From Kills",                   false,  1, false],
  ["FASTER_WANDS",                 "Faster Wands",                      true,  10, false],
  ["EXTRA_SLOTS",                  "Extra Spell Slot",                  true,  10, false],
  ["ALWAYS_CAST",                  "Always Cast",                       true,   5, false],
  ["EXTRA_PERK",                   "Extra Perk",                        true,   3, false],
  ["PERKS_LOTTERY",                "Perk Lottery",                      true,   5, false],
  ["REMOVE_FOG_OF_WAR",            "All-Seeing Eye",                    false,  1, false],
  ["GLOBAL_GORE",                  "Essence Of Spirits",                false,  1, false],
  ["WORM_ATTRACTOR",               "Worm Attractor",                    false,  1, false],
  ["WORM_DETRACTOR",               "Worm Detractor",                    false,  1, false],
  ["WORM_SOMETIMES",               "Worm Sometimes",                    false,  1, false],
  ["SAVING_GRACE",                 "Saving Grace",                      false,  1, false],
  ["GLASS_CANNON",                 "Glass Cannon",                      false,  1, false],
  ["STRONG_KICK",                  "Strong Kick",                       false,  1, false],
  ["ATTACK_FOOT",                  "Leggy Feet",                        true,   5, false],
  ["EXTRA_MONEY",                  "Extra Gold",                        true,   3, false],
  ["EXTRA_MONEY_TRICK_KILL",       "Riches",                            false,  1, false],
  ["TRICK_BLOOD_MONEY",            "Blood Money",                       false,  1, false],
  ["MEGA_BEAM_STONE",              "Mega Beam Stone",                   false,  1, false],
  ["LOW_RECOIL",                   "Low Recoil",                        false,  1, false],
  ["STEADY_HAND",                  "Steady Hand",                       false,  1, false],
  ["HOMUNCULUS",                   "Homunculus",                        false,  1, false],
  ["ELECTRICITY_IMMUNITY",         "Electricity Immunity",              false,  1, false],
  ["FIRE_IMMUNITY",                "Fire Immunity",                     false,  1, false],
  ["EXPLOSION_IMMUNITY",           "Explosion Immunity",                false,  1, false],
  ["MELEE_IMMUNITY",               "Melee Immunity",                    false,  1, false],
  ["PROJECTILE_IMMUNITY",          "Projectile Immunity",               false,  1, false],
  ["DRILL_IMMUNITY",               "Drill Immunity",                    false,  1, false],
  ["ICE_IMMUNITY",                 "Ice Immunity",                      false,  1, false],
  ["SLICE_IMMUNITY",               "Slice Immunity",                    false,  1, false],
  ["TOXIC_IMMUNITY",               "Toxic Immunity",                    false,  1, false],
  ["RADIOACTIVITY_IMMUNITY",       "Radioactivity Immunity",            false,  1, false],
  ["TELEPORTITIS",                 "Teleportitis",                      false,  1, false],
  ["TELEPORTITIS_DODGE",           "Teleportitis Dodge",                false,  1, false],
  ["FASTER_MOVEMENT",              "Faster Movement",                   true,   3, false],
  ["SLOWER_MOVEMENT",              "Slower Movement",                   false,  1, false],
  ["LOW_HP_DAMAGE_BOOST",          "Low HP Damage Boost",               true,   3, false],
  ["HIGH_GRAVITY",                 "High Gravity",                      false,  1, false],
  ["LOW_GRAVITY",                  "Low Gravity",                       true,   3, false],
  ["LEVITATION_TRAIL",             "Levitation Trail",                  true,   3, false],
  ["ANGRY_LEVITATION",             "Angry Levitation",                  true,   3, false],
  ["EDIT_WANDS_EVERYWHERE",        "Tinker With Wands Everywhere",      false,  1, false],
  ["UNLIMITED_SPELLS",             "Unlimited Spells",                  false,  1, false],
  ["NO_MORE_SHUFFLE",              "No More Shuffle",                   false,  1, false],
  ["GOLD_IS_FOREVER",              "Gold Is Forever",                   true,   3,  true],
  ["PEACE_WITH_GODS",              "Peace With Gods",                   false,  1, false],
  ["GENOMICS",                     "Genomics",                          false,  1, false],
  ["GENOME_MORE_LOVE",             "Genome More Love",                  false,  1, false],
  ["GENOME_MORE_HATRED",           "Genome More Hatred",                false,  1, false],
  ["MAP",                          "Map",                               false,  1, false],
  ["ADVENTURER",                   "Adventurer",                        false,  1, false],
  ["EXTRA_SHOP_ITEM",              "Extra Item In Holy Mountain",       true,   3,  true],
  ["ATTRACT_ITEMS",                "Item Radar",                        false,  1, false],
  ["FOOD_CLOCK",                   "Food Clock",                        false,  1, false],
  ["TELEKINESIS",                  "Telekinesis",                       false,  1, false],
  ["LIGHT",                        "Bright",                            true,   3, false],
  ["DARKNESS",                     "Dark",                              false,  1, false],
  ["HP_REGENERATION",              "HP Regeneration",                   true,   3, false],
  ["HP_REGENERATION_TINY",         "Tiny HP Regeneration",              true,  10, false],
  ["VAMPIRISM",                    "Vampirism",                         false,  1, false],
  ["BLOODY_CURSE",                 "Bloody Curse",                      false,  1, false],
  ["CONTACT_DAMAGE",               "Contact Damage",                    false,  1, false],
  ["FIRE_BURST",                   "Fire Burst",                        false,  1, false],
  ["ELECTRICITY",                  "Electricity",                       true,   3, false],
  ["BREATH_OF_FIRE",               "Breath Of Fire",                    false,  1, false],
  ["FAST_PROJECTILES",             "Faster Projectiles",                false,  1, false],
  ["SLOW_PROJECTILES",             "Slower Projectiles",                false,  1, false],
  ["EXTRA_BOUNCE",                 "Extra Bounce",                      false,  1, false],
  ["REPELLING_CAPE",               "Repelling Cape",                    false,  1, false],
  ["INVISIBILITY",                 "Invisibility",                      false,  1, false],
  ["WAND_RADAR",                   "Wand Radar",                        false,  1, false],
  ["ABILITY_ACTIONS_MATERIALIZED", "Wands Materialized",                false,  1, false],
  ["REVENGE_BULLETS",              "Revenge: Bullets",                  false,  1, false],
  ["REVENGE_TENTACLE",             "Revenge: Tentacle",                 false,  1, false],
  ["REVENGE_RATS",                 "Revenge: Rats",                     false,  1, false],
  ["REVENGE_EXPLOSION",            "Revenge: Explosion",                false,  1, false],
  ["GAMBLE",                       "Gamble",                            false,  1, false],
  ["LUKKI_MINION",                 "Lukki Minion",                      false,  1, false],
  ["TOXIC_TO_GOLD",                "Toxic To Gold",                     false,  1, false],
  ["PROTECTION_ALL",               "Stainless Armour",                  true,   5, false],
  ["PLAGUE_RATS",                  "Plague Rats",                       true,   3, false],
  ["VOMIT_RATS",                   "Vomit Rats",                        true,   3, false],
  ["CORDYCEPS",                    "Cordyceps",                         false,  1, false],
  ["FUNGAL_COLONY",                "Fungal Colony",                     false,  1, false],
  ["HUNGER",                       "Hunger",                            false,  1, false],
  ["WEAKNESS",                     "Weakness",                          false,  1, false],
  ["HEARTS_MORE_EXTRA_HP",         "More HP",                           true,  10, false],
  ["HEARTS_MORE",                  "Healthy Exploration",               true,  10, false],
  ["HEARTS_ADDICT",                "Heart Addict",                      false,  1, false],
  ["RESPAWN",                      "Immortal",                          false,  1, false],
  ["FASTING",                      "Fasting",                           false,  1, false],
  ["MOVEMENT_FASTER_SWIMMING",     "Swimmer",                           false,  1, false],
  ["FASTER_LEVITATION",            "Faster Levitation",                 false,  1, false],
  ["OIL_BLOOD",                    "Oil Blood",                         false,  1, false],
  ["SLIME_BLOOD",                  "Slime Blood",                       false,  1, false],
  ["WORM_BLOOD",                   "Worm Blood",                        false,  1, false],
  ["ACID_BLOOD",                   "Acid Blood",                        false,  1, false],
  ["WATER_BREATH",                 "Breathless",                        false,  1, false],
  ["CURSE_WITHER_PROTECTION",      "Protection From Withering",         false,  1, false],
  ["CURSE_WITHER",                 "Withering Touch",                   false,  1, false],
  ["ABILITY_ITEMS_ELECTRICITY",    "Tinker W. Wands Anywhere (Elec)",  false,  1, false],
  ["LASER_AIM",                    "Laser Aim",                         false,  1, false],
  ["MOON_RADAR",                   "Orb Radar",                         false,  1, false],
  ["EXPLOSIVE_CORPSES",            "Exploding Corpses",                 false,  1, false],
  ["EXPLOSIVE_DETONATION",         "Explosive Detonation",              false,  1, false],
  ["BURNING_DETONATION",           "Burning Detonation",                false,  1, false],
  ["FEARED_BY_WORMS",              "Feared By Worms",                   false,  1, false],
  ["TENTACLE_EYES",                "Tentacle Eyes",                     false,  1, false],
  ["PERMANENT_SHIELD",             "Permanent Shield",                  true,   3, false],
  ["CRITICAL_HIT",                 "Critical Hit",                      false,  1, false],
  ["RADAR_ENEMY",                  "Enemy Detector",                    false,  1, false],
  ["NO_WAND_EDITING",              "No Wand Editing",                   false,  1, false],
  ["LEGGY_FEET",                   "Leggy Feet (Var)",                  true,   5, false],
];

var PERK_POOL = PERK_LIST.map(function(p) { return { id: p[0], name: p[1] }; });
var PERK_NAME_MAP = Object.fromEntries(PERK_LIST.map(function(p) { return [p[0], p[1]]; }));

if (typeof module !== 'undefined') {
  module.exports = { PERK_LIST, PERK_POOL, PERK_NAME_MAP };
}
